---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: vinywaji
commonAnnotations:
  app.kubernetes.io/repository: "https://github.com/fsinfuhh/vinywaji"

resources:
  - k8s/deployment.yml
  - k8s/service.yml
